version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    ports:
      - "6432:5432"

  api-server:
    links:
    - "postgres:postgres"
    image: goku321/api-server:v0.5
    environment:
      DB_CONN_STR: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
    ports:
      - 8080:8080