version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    ports:
      - 6432:5432

  api-server:
    image: goku321/api-server:v0.3
    environment:
      DB_CONN_STR: "postgres://postgres:postgres@postgres:6432/postgres?sslmode=disable"
    ports:
      - 8080:8080