apiVersion: v1
kind: ReplicationController
metadata:
    name: api-server
spec:
    replicas: 1
    selector:
        app: api-server
    template:
        metadata:
            labels:
                app: api-server
        spec:
            containers:
            - name: api-server
              image: goku321/api-server:v0.5
              command: ["./api-server"]
              env:
              - name: DB_CONN_STR
                value: "postgres://postgres:postgres@postgres-postgresql.default.svc.cluster.local:5432/postgres?sslmode=disable"
              ports:
              - containerPort: 8080